// Playwright CLI run-code. Use a disposable named browser; resets only its local save.
async page=>{
  const check=(v,m)=>{if(!v)throw Error(m);},errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.continue());
  await page.goto('http://localhost:5191/monsoon-kingdoms/');
  await page.evaluate(()=>{sessionStorage.removeItem('ux-reset-done');for(const k of ['monsoon.kingdoms.v1','monsoon.kingdoms.v1.backup','monsoon.preferences'])localStorage.removeItem(k);});
  // Avoid the outgoing page's save handler re-saving the old state.
  await page.addInitScript(()=>{if(!sessionStorage.getItem('ux-reset-done')){for(const k of ['monsoon.kingdoms.v1','monsoon.kingdoms.v1.backup','monsoon.preferences'])localStorage.removeItem(k);sessionStorage.setItem('ux-reset-done','1');}});
  await page.reload();await page.waitForFunction(()=>window.kingdom?.stats.loaded);await page.locator('#loading').waitFor({state:'hidden'});
  const close=()=>page.getByRole('button',{name:'Close panel',exact:true}).click();
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-action="followObjective"]').click();
  check(await page.locator('.army-roster-card').count()===3,'Ready filter should show unlocked troops only');
  const before=await page.evaluate(()=>window.kingdom.screenForCell(12,12));await page.mouse.move(40,500);await page.mouse.wheel(0,600);const after=await page.evaluate(()=>window.kingdom.screenForCell(12,12));check(JSON.stringify(before)===JSON.stringify(after),'Camera moved behind modal');
  await page.screenshot({path:'monsoon-kingdoms/output/playwright/ux-after-army-1440.png'});
  for(const width of [390,320]){await page.setViewportSize({width,height:844});const add=await page.getByRole('button',{name:'Add Talwar Guard',exact:true}).boundingBox();check(add&&add.y+add.height<844,'First troop cannot be used above the fold');await page.screenshot({path:`monsoon-kingdoms/output/playwright/ux-after-army-${width}.png`});}
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-action="uiArmyTools"]').click();await page.locator('[data-action="saveArmyRecipe"]').click();const recipe=await page.evaluate(()=>window.kingdom.state.army);
  await page.locator('[data-action="clearArmy"]').click();check(await page.evaluate(()=>Object.values(window.kingdom.state.army).every(n=>n===0)),'Clear army failed');await page.locator('[data-action="loadArmyRecipe"]').click();check(JSON.stringify(await page.evaluate(()=>window.kingdom.state.army))===JSON.stringify(recipe),'Recipe not restored');
  await page.locator('[data-action="uiArmyTools"]').click();await page.locator('[data-action="uiFilter"][data-value="army:locked"]').click();check(await page.locator('.army-roster-card').count()===7,'Locked troop filter failed');
  await page.locator('[data-action="uiFilter"][data-value="army:ready"]').click();await page.locator('[data-action="quickTrain"]').click();await close();
  const coins=await page.evaluate(()=>window.kingdom.state.resources.coin);await page.locator('[data-action="collectAll"]').click();check(await page.evaluate(()=>window.kingdom.state.resources.coin)>=coins,'Collection damaged balance');
  await page.getByRole('button',{name:'Build',exact:true}).click();await page.locator('[data-action="uiFilter"][data-value="build:defense"]').click();check(await page.locator('.catalog-card').count()===3,'Defense filter wrong');
  await page.setViewportSize({width:320,height:844});await page.screenshot({path:'monsoon-kingdoms/output/playwright/ux-after-build-320.png'});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Build overflows');await close();
  await page.setViewportSize({width:1440,height:1000});const fingerprint=()=>page.evaluate(()=>JSON.stringify({army:window.kingdom.state.army,attempts:window.kingdom.state.ranked.attacksUsed,gems:window.kingdom.state.gems}));const beforeScout=await fingerprint();
  await page.getByRole('button',{name:'Open Royal League',exact:true}).click();await page.locator('[data-action="startRanked"]').click();check(await page.locator('.briefing-map').count()===1,'Scout map missing');check(await fingerprint()===beforeScout,'Scouting consumed army or attempts');
  await page.locator('[data-action="editArmyFromBriefing"]').click();await page.locator('[data-action="reviewBattle"]').click();check(await fingerprint()===beforeScout,'Editing preview consumed attempt');await page.screenshot({path:'monsoon-kingdoms/output/playwright/ux-after-briefing-1440.png'});
  await page.setViewportSize({width:320,height:844});await page.screenshot({path:'monsoon-kingdoms/output/playwright/ux-after-briefing-320.png'});await page.locator('[data-action="closePanel"]').first().click();check(await fingerprint()===beforeScout,'Cancel scout changed army or attempts');
  await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Open Royal League',exact:true}).click();await page.locator('[data-action="startRanked"]').click();await page.locator('[data-action="confirmBattle"]').click();check(await page.evaluate(()=>window.kingdom.state.ranked.attacksUsed)===1,'Confirm should use exactly one attempt');
  await page.locator('[data-action="retreat"]').click();const t=await page.evaluate(()=>window.kingdom.battle.elapsed);await page.waitForTimeout(500);check(await page.evaluate(()=>window.kingdom.battle.elapsed)===t,'Retreat confirmation must pause');await page.getByRole('button',{name:'Keep fighting',exact:true}).click();await page.waitForFunction(previous=>window.kingdom.battle.elapsed>previous,t);
  await page.setViewportSize({width:320,height:844});await page.getByRole('button',{name:'Center village',exact:true}).click();await page.screenshot({path:'monsoon-kingdoms/output/playwright/ux-after-battle-320.png'});
  await page.locator('[data-action="retreat"]').click();await page.locator('[data-action="confirmRetreat"]').click();await page.getByRole('button',{name:'Return to your kingdom',exact:true}).click();check(await page.evaluate(()=>window.kingdom.state.ranked.attacksUsed)===1,'Retreat duplicated ranked attempt');
  await page.reload();await page.waitForFunction(()=>window.kingdom?.stats.loaded);await page.locator('#loading').waitFor({state:'hidden'});await page.locator('#home-actions [data-value="army"]').click();await page.locator('[data-action="uiArmyTools"]').click();check(await page.locator('[data-action="loadArmyRecipe"]').isEnabled(),'Recipe not persisted');await close();
  check(errors.length===0,errors.join('\n'));return {passed:true,errors,viewports:[1440,390,320],flows:['next objective','modal camera lock','troop filters','recipe save clear restore persistence','bulk collection','build categories','scout cancel edit no charge','ranked exact once','retreat pause cancel confirm']};
}
