import { upgradeCost, capacity, upgradeInfo, researchInfo, heroInfo, finishCost, HEROES, getRanked, effectiveUnit, EQUIPMENT, MAX_EQUIPMENT_LEVEL, equipmentRoster, heroSlots } from './rules.js';
import { ConfettiField, countUp, starSequence, flyToHud, curtain, flyStar, enableRipples } from './ui-fx.js';
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number = value => Math.floor(Number(value) || 0).toLocaleString('en-IN');
const clock = seconds => { seconds = Math.max(0, Math.ceil(seconds)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; };
const shapes = {
  lightning:'<path d="m14 2-9 12h6l-1 8 9-13h-6l1-7Z"/>',
  freeze:'<path d="M12 2v20M3 7l18 10M3 17 21 7M9 4l3 3 3-3M9 20l3-3 3 3M4 10l4-1-1-4m10 14-1-4 4-1M4 14l4 1-1 4m10-14-1 4 4 1"/>',
  rage:'<path d="m13 2 1 7 4-4c0 5 4 7 3 11a9 9 0 0 1-18-1c0-4 4-6 4-10l3 6 3-9Z"/>',
  gems:'<path d="m7 3-5 7 10 12 10-12-5-7H7Zm-5 7h20M7 3l5 19 5-19M7 3l-1 7m11-7 1 7"/>',
  research:'<path d="M9 2h6m-5 0v7L4 19a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3L14 9V2M7 15h10"/><circle cx="11" cy="17" r="1"/>',
  hero:'<path d="m3 7 5 4 4-8 4 8 5-4-2 13H5L3 7Zm2 9h14"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',
  coin:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="5"/><path d="M12 8v8m-2-7h3a2 2 0 0 1 0 4h-2"/>',
  grain:'<path d="M12 21V5m0 5c-5 0-6-4-6-4 5 0 6 4 6 4Zm0 5c-5 0-6-4-6-4 5 0 6 4 6 4Zm0 4c-5 0-6-4-6-4 5 0 6 4 6 4Zm0-10c5 0 6-4 6-4-5 0-6 4-6 4Zm0 5c5 0 6-4 6-4-5 0-6 4-6 4Z"/>',
  wood:'<path d="m5 15 9-10 5 4-9 11Z"/><ellipse cx="7" cy="17" rx="3" ry="4" transform="rotate(-45 7 17)"/><path d="m10 12 6-6m-3 9 5-6"/>',
  iron:'<path d="m4 9 4-5h8l4 5-2 10H6L4 9Zm0 0h16M8 4l2 5-1 10m7-15-2 5 1 10"/>',
  build:'<path d="M4 20h16M6 20V10l6-5 6 5v10M9 20v-6h6v6M4 9l8-7 8 7"/>',
  fort:'<path d="M3 21V10h5v11m8 0V10h5v11M8 21V8l4-5 4 5v13M3 10V7m5 3V7m8 3V7m5 3V7M10 21v-6h4v6M1 21h22"/>',
  army:'<path d="m5 3 14 18M4 3l4 1-3 3-1-4Zm15 0L5 21m15-18-4 1 3 3 1-4ZM3 16l6 5m12-5-6 5"/>',
  map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/><path d="m11 9 2 2-2 2"/>',
  book:'<path d="M12 5c-3-3-7-2-9-1v15c3-1 6-1 9 2 3-3 6-3 9-2V4c-2-1-6-2-9 1Zm0 0v16M6 8h3m-3 4h3m6-4h3m-3 4h3"/>',
  rain:'<path d="M6 13a4 4 0 0 1 0-8 6 6 0 0 1 11-1 5 5 0 1 1 1 9H6Zm1 3-1 3m6-3-1 4m6-4-1 3"/>',
  hammer:'<path d="m5 20 9-12m-4-4 3-3 8 6-3 4-8-7ZM3 19l3 2"/>',
  star:'<path d="m12 2 3 6.5 7 .9-5.1 5 .9 7-5.8-3.3-5.8 3.3.9-7-5.1-5 7-.9L12 2Z"/>',
  close:'<path d="m6 6 12 12M6 18 18 6"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  minus:'<path d="M5 12h14"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  up:'<path d="m5 11 7-7 7 7M12 4v16"/>',
  move:'<path d="M12 2v20M2 12h20M9 5l3-3 3 3M9 19l3 3 3-3M5 9l-3 3 3 3m14-6 3 3-3 3"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',
  sound:'<path d="M4 9h4l5-5v16l-5-5H4V9Zm12-2a8 8 0 0 1 0 10m3-13a12 12 0 0 1 0 16"/>',
  mute:'<path d="M4 9h4l5-5v16l-5-5H4V9Zm13 0 5 6m0-6-5 6"/>',
  music:'<path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/>',
  settings:'<path d="m10 3-1 3-3 1-3 3 2 2-1 4 3 2 3-1 3 3 3-2v-3l4-2-1-4-3-1-2-4-4-1Z"/><circle cx="12" cy="12" r="3"/>',
  rotate:'<path d="M20 9a8 8 0 1 0 0 7M20 3v6h-6"/>',
  target:'<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 1v4m0 14v4M1 12h4m14 0h4"/>',
  shield:'<path d="m12 2 8 4v7c0 5-8 9-8 9s-8-4-8-9V6l8-4Z"/><path d="m8 12 3 3 5-6"/>',
  time:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
  ore:'<path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m12 3 4 6-4 3-4-3 4-6Zm-4 6-4-1.5M16 9l4-1.5M12 12v9"/>',
  kit:'<path d="M4 8h16v12H4V8Z"/><path d="M9 8V5a3 3 0 0 1 6 0v3M4 13h16"/>',
  slot:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="M12 8v8m-4-4h8"/>',
  globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18Z"/>',
  trophy:'<path d="M8 4h8v5a4 4 0 0 1-8 0V4Z"/><path d="M8 5H5v2a3 3 0 0 0 3 3m8-5h3v2a3 3 0 0 1-3 3m-4 3v4m-3 3h6"/>',
};
const icon = (name, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name] || shapes.fort}</svg>`;
const button = (action, label, options = {}) => `<button type="button" data-action="${action}" ${options.value != null ? `data-value="${escape(options.value)}"` : ''} class="${options.class || 'button'}" ${options.count ? `data-count="${options.count}"` : ''} ${options.disabled ? 'disabled' : ''} ${options.title ? `aria-label="${escape(options.title)}" title="${escape(options.title)}"` : ''}>${options.icon ? icon(options.icon) : ''}${label}</button>`;
const cost = (value = {}) => `<span class="cost">${Object.entries(value).filter(([, n]) => n > 0).map(([key, n]) => `<span class="cost-${key}" title="${key}">${icon(key)}${number(n)}</span>`).join('')}</span>`;
const stars = (n = 0) => `<span class="stars" aria-label="${n} of 3 stars">${[1,2,3].map(i => icon('star', i <= n ? 'earned' : '')).join('')}</span>`;
const buildingIcons = {fort:'fort',farm:'grain',lumber:'wood',mine:'iron',granary:'build',stepwell:'rain',barracks:'army',camp:'shield',archer_tower:'target',cannon:'target',wall:'shield',market:'coin',laboratory:'research',hero_hall:'hero',gem_mine:'gems'};
const spellNames={lightning:'Lightning',freeze:'Freeze',rage:'Rage'};
const unitTargets={engineer:'walls & defenses',rider:'defenses',healer:'wounded allies',bowler:'clustered structures',miner:'structures beyond walls',yeti:'nearest structure',garuda:'defenses from the air'};
const unitMonograms = { guard:'TG', archer:'BA', engineer:'SE', rider:'MR', elephant:'WE', healer:'MH', bowler:'SB', miner:'TM', yeti:'HY', garuda:'GR' };
const unavailableArt = new Set();
const art = (type, unit = false, level = 1) => {
  const base=`./assets/${unit ? 'units' : 'buildings'}/${type}.png`, requested=!unit&&level>1?`./assets/buildings/levels/${type}/${level}.png`:base,src=unavailableArt.has(requested)?base:requested;
  return `<span class="item-art ${unit ? 'unit-art' : 'building-art'} art-${type}" aria-hidden="true"><img src="${src}" ${src!==base?`data-fallback="${base}"`:''} alt="" loading="lazy">${icon(unit ? (type === 'healer' ? 'rain' : type === 'archer' ? 'target' : 'army') : buildingIcons[type])}<span class="art-monogram">${unit ? unitMonograms[type] : ''}</span></span>`;
};
const buildingLevelName=(spec,level)=>spec.levelNames?.[level-1]||`Level ${level}`;

const heroArt = id => `<span class="hero-art"><img src="./assets/heroes/${id}.png" alt="${escape(HEROES[id]?.name||id)}">${icon('hero')}</span>`;
const countdown = ms => { const n=Math.max(0,Math.ceil(ms/1000)); return n>86400?`${Math.floor(n/86400)}d ${Math.floor(n%86400/3600)}h`:n>3600?`${Math.floor(n/3600)}h ${Math.floor(n%3600/60)}m`:clock(n); };
const statRows=(current,next,keys=['hp','damage','heal','production','capacity'],labels={})=>`<div class="stat-comparison">${keys.filter(k=>(current?.[k]||next?.[k])>0).map(k=>`<div><span>${labels[k]||({hp:'Hit points',damage:'Attack damage',heal:'Healing',production:'Production / min',capacity:'Storage / space',range:'Attack range'})[k]||k}</span><strong>${k==='production'?Math.round(current[k]*600)/10:number(current[k])}</strong>${icon('arrow')}<b>${k==='production'?Math.round(next[k]*600)/10:number(next[k])}</b></div>`).join('')}</div>`;
// Patch only changed text/attributes so timer updates never replace focused controls.
function morph(current, next) {
  if (current.nodeType !== next.nodeType || current.nodeName !== next.nodeName) { current.replaceWith(next.cloneNode(true)); return; }
  if (current.nodeType === Node.TEXT_NODE) { if (current.nodeValue !== next.nodeValue) current.nodeValue = next.nodeValue; return; }
  if (current.nodeType !== Node.ELEMENT_NODE) return;
  for (const attr of [...current.attributes]) if (!next.hasAttribute(attr.name)) current.removeAttribute(attr.name);
  for (const attr of [...next.attributes]) if (current.getAttribute(attr.name) !== attr.value && !(current === document.activeElement && attr.name === 'value')) current.setAttribute(attr.name, attr.value);
  const oldChildren = [...current.childNodes], newChildren = [...next.childNodes];
  for (let i = 0; i < Math.max(oldChildren.length, newChildren.length); i++) {
    if (!newChildren[i]) oldChildren[i]?.remove();
    else if (!oldChildren[i]) current.append(newChildren[i].cloneNode(true));
    else morph(oldChildren[i], newChildren[i]);
  }
}
export class GameUI {
  constructor(actions) {
    this.filters={build:'all',army:'ready'};this.expandedBuild=null;this.expandedUnit=null;this.armyTools=false;this.battleDeck=[];this.resourcesOpen=false;
    this.heroFocus=null;this.heroDetails=new Set();this.upgradeTab='stats';this.galleryBuilding=null;this.galleryLevel=1;this.equipHero=null;this.equipSlot=null;this.actions = actions; this.lastPanel = null; this.snapshot = null; this.result = null; this.html = new Map();
    this.root = document.getElementById('ui');
    this.root.innerHTML = `<section id="orientation-guide" aria-labelledby="orientation-title"><div class="rotate-device-art">${icon('rotate')}</div><span class="eyebrow">CROWN OF BHARAT</span><h2 id="orientation-title">Rotate to continue</h2><p>Turn your phone sideways for a clear view of your kingdom.</p><small>Your progress stays saved on this device.</small></section><header id="home-hud"></header><header id="battle-hud"></header><aside id="world-label"></aside><aside id="objective-actions" aria-label="Your next objective"></aside><nav id="side-tools" aria-label="Kingdom tools"></nav><nav id="camera-tools" aria-label="Camera controls"></nav><footer id="home-actions"></footer><section id="context-actions" aria-label="Selected building"></section><section id="placement-actions" aria-label="Place building"></section><section id="troop-actions" aria-label="Deploy troops"></section><section id="panel-host"></section><section id="result-host"></section><div id="toast" role="status" aria-live="polite"></div><div id="loading" role="status"><div class="loading-mark"><img class="brand-emblem" src="./assets/branding/crown-icon-192.png" alt="" width="64" height="64"></div><span class="eyebrow">AN ORIGINAL STRATEGY ADVENTURE</span><h1><img class="game-title" src="./assets/branding/crown-of-bharat-title.webp" alt="Crown of Bharat" width="1774" height="887"></h1><p>Every kingdom begins with a little rain.</p><div class="loading-track"><div id="loading-progress"></div></div><span id="loading-label">Preparing your kingdom…</span></div>`;
    enableRipples(this.root);
    this.root.addEventListener('error', event => {const img=event.target;if(img.tagName!=='IMG')return;const fallback=img.dataset.fallback;if(fallback){unavailableArt.add(img.getAttribute('src'));img.src=fallback;delete img.dataset.fallback;}else img.hidden=true;},true);
    this.orientationQuery=matchMedia('(orientation: portrait) and (max-width: 1024px)');
    const syncOrientation=()=>{const blocked=this.orientationQuery.matches;document.body.classList.toggle('portrait-blocked',blocked);for(const child of this.root.children)if(!['orientation-guide','loading'].includes(child.id))child.inert=blocked;window.dispatchEvent(new CustomEvent('kingdom-orientation',{detail:{blocked}}));};
    this.orientationQuery.addEventListener('change',syncOrientation);syncOrientation();
    this.root.addEventListener('click', event => {
      const target = event.target.closest('[data-action]'); if (!target || target.disabled) return;
      const { action, value } = target.dataset;
      if(action==='uiUpgradeTab'){this.upgradeTab=value==='appearance'?'appearance':'stats';this.render(this.snapshot);return;}
      if(action==='openUpgrade'){this.upgradeTab='stats';this.galleryBuilding=null;}
      if(action==='uiGallery'){this.galleryBuilding=this.galleryBuilding===value?null:value;this.galleryLevel=this.snapshot.state.buildings.find(b=>b.id===value)?.level||1;this.render(this.snapshot);return;}
      if(action==='uiGalleryLevel'){this.galleryLevel=Number(value);this.render(this.snapshot);return;}
      if(action==='uiFilter'){const [panel,filter]=value.split(':');this.filters[panel]=filter;this.expandedBuild=this.expandedUnit=null;this.render(this.snapshot);document.querySelector('.panel-content')?.scrollTo(0,0);return;}
      if(action==='uiBuildDetail'||action==='uiUnitDetail'){const key=action==='uiBuildDetail'?'expandedBuild':'expandedUnit';this[key]=this[key]===value?null:value;this.render(this.snapshot);return;}
      if(action==='uiHeroFocus'){if(Object.hasOwn(HEROES,value))this.heroFocus=value;this.render(this.snapshot);document.querySelector('.panel-content')?.scrollTo(0,0);return;}
      if(action==='uiHeroDetails'){if(this.heroDetails.has(value))this.heroDetails.delete(value);else this.heroDetails.add(value);this.render(this.snapshot);return;}
      if(action==='uiEquip'){this.equipHero=this.equipHero===value?null:value;this.equipSlot=null;this.render(this.snapshot);return;}
      if(action==='uiSlot'){const [hero,index]=value.split(':');this.equipSlot=this.equipSlot===value?null:value;this.equipHero=hero;void index;this.render(this.snapshot);return;}
      if(action==='equipItem'){const [hero,index,item]=value.split(':');this.actions.equipItem?.(hero,Number(index),item||null);this.equipSlot=null;return;}
      if(action==='uiResources'){this.resourcesOpen=!this.resourcesOpen;this.render(this.snapshot);return;}
      if(action==='uiArmyTools'){this.armyTools=!this.armyTools;this.render(this.snapshot);return;}
      if (action === 'cancelSpell') { this.actions.selectSpell?.(null); return; }
      if (action === 'openLeague') { this.actions.setAttackTab?.('ranked'); this.actions.openPanel?.('attack'); return; }
      if (action === 'dismissResult') { this.result = null; this.stopResultFx(); this.update('result-host', ''); this.actions.closePanel?.(); document.getElementById('world').focus(); return; }
      if (action === 'saveName') { const input = document.getElementById('kingdom-name'); this.actions.saveName?.(input.value.trim()); return; }
      if (action === 'train' || action === 'removeTroop') { this.actions[action]?.(value, Number(target.dataset.count) || 1); return; }
      if (action === 'finish' || action === 'confirmFinish') { const [kind,id] = value.split(':'); this.actions[action]?.(kind,id); return; }
      this.actions[action]?.(value);
    });
    this.root.addEventListener('change', event => { if(event.target.id==='graphics-quality') this.actions.setQuality?.(event.target.value); });
    this.root.addEventListener('input', event => { const kind=event.target.dataset?.volume; if(kind) this.actions.setVolume?.(kind, event.target.value); });
    this.root.addEventListener('submit', event => { if (event.target.id === 'name-form') { event.preventDefault(); this.actions.saveName?.(document.getElementById('kingdom-name').value.trim()); } });
    document.addEventListener('keydown', event => {
      if(this.orientationQuery.matches)return;
      if (event.key === 'Escape') {
        if (this.result) { this.result = null; this.update('result-host', ''); this.actions.closePanel?.(); }
        else if (this.resourcesOpen) { this.resourcesOpen=false;this.render(this.snapshot); }
        else if (this.snapshot?.selectedSpell) this.actions.selectSpell?.(null);
        else if (this.snapshot?.placing) this.actions.cancelPlacement?.();
        else if (this.snapshot?.panel==='retreat') this.actions.cancelRetreat?.();
        else if (this.snapshot?.panel) this.actions.closePanel?.();
        else this.actions.selectBuilding?.(null);
      }
      if(event.target.closest?.('.upgrade-tabs')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){
        const tabs=[...this.root.querySelectorAll('.upgrade-tabs [role=tab]')],index=tabs.indexOf(event.target);
        const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowLeft'?-1:1)+tabs.length)%tabs.length;
        event.preventDefault();tabs[next].click();this.root.querySelectorAll('.upgrade-tabs [role=tab]')[next]?.focus();return;
      }
      if (event.key !== 'Tab') return;
      const dialog = this.root.querySelector('[role="dialog"]'); if (!dialog) return;
      const focusable = [...dialog.querySelectorAll('button:not(:disabled),input:not([type=hidden]),select,a[href],[tabindex="0"]')].filter(el=>el.tabIndex>=0&&el.getClientRects().length&&!el.closest('[hidden],[inert]'));
      if (!focusable.length) return;
      const first = focusable[0], last = focusable.at(-1);
      if (event.shiftKey && (document.activeElement === first || !dialog.contains(document.activeElement))) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && (document.activeElement === last || !dialog.contains(document.activeElement))) { event.preventDefault(); first.focus(); }
    });
  }
  update(id, html) {
    if (this.html.get(id) === html) return;
    this.html.set(id, html);
    const host = document.getElementById(id), template = document.createElement('template'); template.innerHTML = html;
    const wrapper = host.cloneNode(false); wrapper.append(template.content); morph(host, wrapper);
  }
  render(snapshot) {
    this.snapshot = snapshot;
    const { state:s, catalog = {}, units = {}, raids = [], battle:b, mode, panel } = snapshot;
    if(panel)this.resourcesOpen=false;
    if(panel==='army'&&panel!==this.lastPanel)this.armyTools=false;
    if (!s) return;
    const cap = snapshot.capacity || capacity(s), fort=s.buildings.find(x=>x.type==='fort'), home=mode!=='battle'; this.cap=cap;
    const ranked=snapshot.ranked || getRanked(s), activeResearch=s.research, workshop=s.buildings.find(b=>b.type==='laboratory'), hasHeroHall=s.buildings.some(b=>b.type==='hero_hall'&&b.level>0);
    this.root.classList.toggle('has-selection',!!snapshot.selectedBuilding);this.root.classList.toggle('battle-mode',!home);this.root.classList.toggle('has-panel',!!panel);this.root.classList.toggle('is-placing',!!snapshot.placing);
    this.update('home-hud',home ? `<div class="player-cluster"><button class="player-medallion" data-action="openPanel" data-value="settings" aria-label="Kingdom settings"><span class="portrait">${icon('fort')}<b>${fort?.level||1}</b></span><span><strong>${escape(s.name)}</strong><small>Taj level ${fort?.level||1}</small></span></button>${button('openLeague',`${icon('shield')}<span>${escape(ranked.league)}<b>${number(ranked.score)}</b></span>`,{value:'attack',class:'league-badge',title:'Open Royal League'})}</div><div class="builder-stack">${button('openPanel',`${icon('hammer')}<span><b>${cap.builders-cap.busy}/${cap.builders}</b><small>Builders</small></span>`,{value:'builders',class:'builder-chip',title:'Builders: running work and suggested upgrades'})}${button('openPanel',`${icon('research')}<span><b>${activeResearch?clock((activeResearch.readyAt-Date.now())/1000):workshop?(workshop.level>0?'Ready':'Building'):'Locked'}</b><small>Research</small></span>`,{value:'research',class:'builder-chip research-chip',title:'Open Royal Workshop'})}</div><div class="resource-bar">${['coin','grain','wood','iron'].map(key=>`<button data-action="uiResources" class="resource resource-${key}" aria-label="${key} storage" title="${key}: ${number(s.resources[key])} / ${number(cap.storage[key])}"><span class="resource-fill" style="width:${Math.min(100,s.resources[key]/cap.storage[key]*100)}%"></span><span class="resource-caption"><small>${key}</small><strong>${number(s.resources[key])}</strong><span class="resource-cap">/ ${number(cap.storage[key])}</span></span><span class="resource-icon">${icon(key)}</span></button>`).join('')}${button('openPanel',`<span class="resource-caption"><small>GEMS</small><strong>${number(s.gems)}</strong></span><span class="resource-icon">${icon('gems')}</span>${icon('plus')}`,{value:'gems',class:'resource resource-gems',title:'Gems and builders'})}${this.resourcesOpen?`<div class="resource-storage"><div><strong>Your storage</strong>${button('uiResources','',{icon:'close',class:'icon-button',title:'Close storage details'})}</div>${['coin','grain','wood','iron'].map(k=>`<p>${icon(k)}<span>${k}</span><strong>${number(s.resources[k])}<small> / ${number(cap.storage[k])}</small></strong></p>`).join('')}<span>Upgrade the Royal Granary for more space.</span></div>`:''}</div>`:'');
    this.update('world-label','');
    const coach=snapshot.tutorial;
    this.update('objective-actions',home&&!panel&&!snapshot.placing&&!snapshot.selectedBuilding&&(coach||snapshot.objective)?`<div class="objective-chip"><button data-action="${coach?'tutorialAction':'followObjective'}" class="objective-follow" title="${escape(coach?.body||snapshot.objective?.detail||'')}">${icon('target')}<span><small>${coach?`GUIDE ${coach.number}/${coach.total}`:'NEXT STEP'}</small><strong>${escape(coach?.title||snapshot.objective?.title)}</strong></span>${icon('arrow')}</button>${button(coach?'skipTutorial':'dismissObjective','',{icon:'close',class:'objective-dismiss',title:coach?'Dismiss guided start':'Dismiss objective'})}</div>`:'');
    this.update('side-tools',home?`${button('openPanel','<span>Chronicle</span>',{value:'chronicle',icon:'book',class:'side-button',title:'Open chronicle'})}${button('openPanel','',{value:'help',icon:'info',class:'icon-button',title:'Field guide'})}${button('collectAll',`${icon('coin')}<span>Collect all</span>`,{class:'button collect-all',disabled:!snapshot.collectable})}`:'');
    this.update('camera-tools',`${button('toggleMute','',{icon:snapshot.soundEnabled===false?'mute':'sound',class:'icon-button sound-quick',title:snapshot.soundEnabled===false?'Unmute sound':'Mute sound'})}${button('setCamera','',{value:'zoomIn',icon:'plus',class:'icon-button',title:'Zoom in'})}${button('setCamera','',{value:'zoomOut',icon:'minus',class:'icon-button',title:'Zoom out'})}${button('setCamera','',{value:'rotate',icon:'rotate',class:'icon-button',title:'Rotate view'})}${button('setCamera','',{value:'reset',icon:'target',class:'icon-button',title:'Center village'})}`);
    this.update('home-actions',home?`<div class="raid-cluster">${button('openPanel',`${icon('army')}<strong>ATTACK!</strong>`,{value:'attack',class:'campaign-button',title:'Attack'})}</div><div class="home-controls">${button('openPanel',`${icon('army')}<span>Army<small>${cap.used}/${cap.army}</small></span>`,{value:'army',class:'army-button'})}${button('openPanel',`${icon(hasHeroHall?'hero':'lock')}<span>Heroes${hasHeroHall?'':'<small>Build Hall</small>'}</span>`,{value:'heroes',class:'army-button hero-home-button'})}${button('openPanel',`${icon('hammer')}<span>Shop</span>`,{value:'build',class:'build-button',title:'Build: open building shop'})}</div>`:'');
    const selected=typeof snapshot.selectedBuilding==='object'?snapshot.selectedBuilding:s.buildings.find(x=>x.id===snapshot.selectedBuilding);
    this.update('context-actions',home&&selected&&!panel&&!snapshot.placing?this.context(selected,catalog):'');
    const placing=snapshot.placing,wall=placing?.line;let count=wall?.cells?.length||0;
    this.update('placement-actions',home&&placing?`<div class="placement-card"><span class="placement-icon">${icon(snapshot.placementValid?'check':'move')}</span><div><small>${wall?'CONTINUOUS WALL TOOL':placing.id?'MOVING BUILDING':'PLACE A BUILDING'}</small><strong>${wall?`Rampart line${count?` · ${count} segments`:''}`:escape(catalog[placing.type]?.name||'Choose a location')}</strong><p class="${snapshot.placementValid?'':'invalid'}">${escape(snapshot.placementReason||(wall?(snapshot.wallStart?'Tap the second end of your straight wall.':'Tap the first end, then tap the second end.'):snapshot.placementValid?'Tap the ground to position, then confirm.':'Choose an open tile.'))}</p>${wall&&count?cost(Object.fromEntries(Object.entries(catalog.wall.cost).map(([k,v])=>[k,v*count]))):''}</div>${button('cancelPlacement','',{icon:'close',class:'icon-button',title:'Cancel placement'})}${button('confirmPlacement',wall?'Build walls':'Place',{icon:'check',class:'button primary',disabled:!snapshot.placementValid})}</div>`:'');
    this.update('battle-hud',!home&&b?`<div class="battle-title"><small>${b.kind==='practice'?'DEFENSE PRACTICE':b.kind==='ranked'?'ROYAL LEAGUE · LOCAL AI':b.kind==='online'?'ONLINE · REAL PLAYER':'CAMPAIGN RAID'}</small><strong>${escape(b.opponent?.name||b.raid?.name||raids.find(r=>r.id===b.raidId)?.name||'For the valley')}</strong></div><div class="battle-score">${stars(b.stars)}<strong>${Math.floor(b.destruction||0)}<small>%</small></strong><span>TAJ · 50% · 100%</span></div><div class="battle-time ${b.duration-b.elapsed<30?'urgent':''}">${icon('time')}<strong>${clock(b.duration-b.elapsed)}</strong></div>${button('retreat','Retreat',{class:'retreat-button',icon:'arrow'})}`:'');
    if(b?.id!==this.lastBattleId){this.battleDeck=Object.keys(b?.reserve||{}).filter(id=>b.reserve[id]>0);this.lastBattleId=b?.id;}
    const hero=b?.hero,heroUnit=hero?b.units.find(u=>u.id===hero.unitId):null,heroSpec=hero?HEROES[hero.id]:null,heroAbilityUntil=Math.max(heroUnit?.rushUntil||0,heroUnit?.abilityUntil||0);
    const spells=snapshot.spells||{},aim=snapshot.selectedSpell,aimName=spellNames[aim]||spells[aim]?.name||aim;
    const spellBar=`<div class="spell-bar" aria-label="Battle spells">${Object.entries(spells).filter(([id])=>id!=='rain').map(([id,spell])=>{const remaining=b?.spells?.[id]||0;return `<button class="spell-button spell-${id} ${aim===id?'selected':''}" data-action="selectSpell" data-value="${id}" ${!remaining?'disabled':''} aria-pressed="${aim===id}" aria-label="${escape(spellNames[id]||spell.name)}, ${remaining} casts remaining" title="${escape(spell.name)}: ${escape(spell.description)}">${icon(id)}<span><strong>${escape(spellNames[id]||spell.name)}</strong><small>${remaining?`${remaining} left · aim`:b?.rainAvailable?'Used':'Stepwell'}</small></span></button>`;}).join('')}<button class="spell-button spell-rain" data-action="castRain" ${!b?.rainAvailable||b?.rainUsed?'disabled':''} aria-label="Monsoon, ${b?.rainUsed?'used':b?.rainAvailable?'heal army':'requires stepwell'}">${icon('rain')}<span><strong>Monsoon</strong><small>${b?.rainUsed?'Used':!b?.rainAvailable?'Stepwell':'Heal army'}</small></span></button></div>`;
    this.update('troop-actions',!home&&b?`<div class="deployment-hint ${aim?'spell-aiming':''}">${icon(aim||'target')}<span>${aim?`${escape(aimName)} — tap the battlefield` : snapshot.selectedTroop==='hero'?(hero?.deployed?'Your hero is fighting — select troops or use the hero ability':`${escape(hero?.name||'Hero')} selected — tap the outer edge`):snapshot.selectedTroop?`${escape(units[snapshot.selectedTroop]?.name)} selected — tap the outer edge`:Object.values(b.reserve).some(n=>n>0)?'Select a troop, then tap the outer edge':(b.hero?'All troops deployed · use spells or your hero ability':'All troops deployed · use remaining spells')}</span>${aim?button('cancelSpell','Cancel',{class:'button cancel-aim'}):''}</div>${spellBar}<div class="deck-caption">Your army · swipe cards to browse</div><div class="troop-tray"><div class="troop-scroll" aria-label="Troops · swipe to browse">${Object.entries(units).filter(([id])=>this.battleDeck.includes(id)).map(([id,u])=>`<button class="troop-card ${snapshot.selectedTroop===id&&!aim?'selected':''}" data-action="selectTroop" data-value="${id}" ${!b.reserve[id]?'disabled':''} aria-label="Deploy ${escape(u.name)}, ${b.reserve[id]||0} remaining" aria-pressed="${snapshot.selectedTroop===id&&!aim}"><span class="troop-count">×${b.reserve[id]||0}</span>${art(id,true)}<span class="troop-level">${b.unitStats?.[id]?.level||s.unitLevels[id]}</span><span class="troop-label" data-short="${id==='elephant'?'Elephant':id.charAt(0).toUpperCase()+id.slice(1)}">${escape(u.name)}</span></button>`).join('')}</div><div class="battle-abilities">${hero?`<button class="battle-hero ${snapshot.selectedTroop==='hero'&&!aim?'selected':''}" data-action="${hero.deployed?'heroAbility':'selectHeroDeploy'}" ${hero.deployed&&(hero.abilityUsed||!heroUnit?.hp)?'disabled':''} aria-label="${hero.deployed?`Activate ${heroSpec.ability}`:`Deploy ${hero.name}`}">${heroArt(hero.id)}<span><strong>${escape(heroSpec?.shortName||heroSpec?.name||hero.name||hero.id)} <b>${hero.level}</b></strong><small>${!hero.deployed?'Deploy hero':heroUnit?.hp<=0?'Defeated':heroAbilityUntil>b.elapsed?`Active ${Math.ceil(heroAbilityUntil-b.elapsed)}s`:hero.abilityUsed?'Ability used':heroSpec.ability}</small></span>${hero.deployed?`<span class="hero-life"><i style="width:${Math.max(0,heroUnit?.hp||0)/(heroUnit?.maxHp||1)*100}%"></i></span>`:''}</button>`:''}</div></div>`:'');
    this.update('panel-host',panel?this.panel(panel,snapshot):'');
    if(panel!==this.lastPanel){clearTimeout(this.toastTimer);document.getElementById('toast').classList.remove('visible');if(panel){const content=document.querySelector('#panel-host .panel-content');if(content)content.scrollTop=0;this.previousFocus=document.activeElement;requestAnimationFrame(()=>document.querySelector('#panel-host .panel-close')?.focus());}else if(this.lastPanel)this.previousFocus?.isConnected&&this.previousFocus.focus();this.lastPanel=panel;}
  }
  context(b,catalog) {
    const c=catalog[b.type],busy=b.readyAt>0,s=this.snapshot.state,finish=busy?finishCost(s,'building',b.id):null,info=upgradeInfo(s,b.id);
    const direct={camp:['army','army','Train'],barracks:['army','army','Train'],laboratory:['research','research','Research'],hero_hall:['heroes','hero','Heroes']}[b.type];
    return `<div class="context-card"><div class="context-title"><strong>${escape(c.name)} <span>Level ${b.level}</span></strong>${busy?`<small>${icon('time')} ${clock((b.readyAt-Date.now())/1000)} remaining</small>`:''}</div>${button('selectBuilding','',{icon:'close',class:'icon-button context-dismiss',title:'Deselect building'})}<div class="context-buttons">${busy?button('finish',`${icon('gems')}<strong>Finish now</strong>`,{value:`building:${b.id}`,class:'context-action context-upgrade',title:`Finish ${c.name} for ${finish?.cost||1} gems`}):button('openUpgrade',`${icon(b.level<c.maxLevel?'up':'info')}<strong>${b.level<c.maxLevel?'Upgrade':'Details'}</strong>`,{value:b.id,class:'context-action context-upgrade',title:b.level<c.maxLevel?`Upgrade ${c.name} to level ${info.nextLevel}`:`Building details: ${c.name}`})}${c.production&&!busy?button('collect',`${icon(c.production.resource)}<strong>Collect ${number(b.stored)}</strong>`,{value:b.id,class:'context-action context-collect',disabled:b.stored<1,title:`Collect ${number(b.stored)} ${c.production.resource}`}):''}${direct&&!busy?button('openPanel',`${icon(direct[1])}<strong>${direct[2]}</strong>`,{value:direct[0],class:'context-action context-direct'}):''}${button('move',`${icon('move')}<strong>Move</strong>`,{value:b.id,class:'context-action',title:'Move building',disabled:busy})}</div></div>`;
  }
  panelShell(name,title,eyebrow,content,toolbar='',closeAction='closePanel') {
    const labels={build:'Shop',army:'Army',heroes:'Heroes',attack:'Battle',map:'Battle',ranked:'Battle',online:'Battle',settings:'Kingdom',builders:'Builders',research:'Research',gems:'Treasury',upgrade:'Building',briefing:'Briefing'};
    const topLevel=['build','army','heroes','attack','map','ranked','online','settings'].includes(name);
    const selected=['map','ranked','online'].includes(name)?'attack':name;
    const navigation=topLevel?`<nav class="panel-nav" aria-label="Game menus">${[['build','hammer','Shop'],['army','army','Army'],['heroes','hero','Heroes'],['attack','map','Battle'],['settings','settings','Kingdom']].map(([id,glyph,label])=>`<button type="button" data-action="openPanel" data-value="${id}" ${id===selected?'aria-current="page"':''}>${icon(glyph)}<span>${label}</span></button>`).join('')}</nav>`:'';
    const parent=this.snapshot?.parentPanel;
    return `<section class="game-panel panel-${name}" role="dialog" aria-modal="true" aria-labelledby="panel-title"><header class="panel-header"><div class="panel-heading">${parent?button('backPanel','',{icon:'arrow',class:'icon-button panel-back',title:`Back to ${labels[parent]||parent}`}):''}<div><span class="eyebrow">${eyebrow}</span><h2 id="panel-title">${title}</h2></div></div>${button(closeAction,'',{icon:'close',class:'icon-button panel-close',title:'Close panel'})}</header>${navigation}${toolbar}<div class="panel-content">${content}</div></section>`;
  }
  attackTabs(selected) {return `<nav class="attack-tabs" aria-label="Battle type">${[['campaign','map','Campaign','Six river roads'],['ranked','shield','Royal League','Local AI rivals'],['online','globe','Online','Real kingdoms']].map(([id,glyph,title,detail])=>button('setAttackTab',`${icon(glyph)}<span><strong>${title}</strong><small>${detail}</small></span>`,{value:id,class:`battle-tab ${selected===id?'active':''}`})).join('')}</nav>`;}
  buildersPanel(snapshot) {
    const s=snapshot.state,catalog=snapshot.catalog,cap=this.cap;
    const jobs=[...s.buildings.filter(b=>b.readyAt).map(b=>({kind:'building',id:b.id,name:catalog[b.type].name,level:b.upgradingTo||b.level,art:art(b.type,false,b.level)})),...Object.entries(s.heroes||{}).filter(([,h])=>h.readyAt).map(([id,h])=>({kind:'hero',id,name:HEROES[id].name,level:h.upgradingTo||h.level,art:heroArt(id)}))];
    const suggestions=s.buildings.filter(b=>!b.readyAt&&b.level<catalog[b.type].maxLevel).map(b=>({b,info:upgradeInfo(s,b.id)})).sort((a,b)=>Number(b.info.canUpgrade)-Number(a.info.canUpgrade)||Number(b.b.type==='fort')-Number(a.b.type==='fort'));
    return this.panelShell('builders','Royal builders','KEEP YOUR KINGDOM GROWING',`<div class="builders-summary">${icon('hammer')}<span><strong>${cap.builders-cap.busy} of ${cap.builders} builders ready</strong><small>${cap.busy?`${cap.busy} projects in progress`:'Choose the next improvement below'}</small></span>${button('openPanel','More builders',{value:'gems',icon:'plus',class:'button secondary'})}</div>${jobs.length?`<h3 class="section-title">Work in progress</h3><div class="builder-jobs">${jobs.map(j=>{const f=finishCost(s,j.kind,j.id);return `<article class="builder-project">${j.art}<div><h3>${escape(j.name)}</h3><p>Level ${j.level} · ${clock(f.remaining||0)} remaining</p></div>${button('finish',`Finish ${icon('gems')} ${number(f.cost||1)}`,{value:`${j.kind}:${j.id}`,class:'button primary'})}</article>`;}).join('')}</div>`:''}<h3 class="section-title">Suggested upgrades</h3><div class="builder-suggestions">${suggestions.map(({b,info})=>`<article class="builder-project ${info.canUpgrade?'is-ready':''}">${art(b.type,false,b.level)}<div><h3>${escape(catalog[b.type].name)} <small>Level ${b.level} → ${info.nextLevel}</small></h3>${cost(info.cost)}<p>${info.canUpgrade?`${clock(info.duration)} · Builder ready`:escape(info.reason)}</p></div>${button('openUpgrade','View upgrade',{value:b.id,icon:'up',class:'button secondary'})}</article>`).join('')||'<p class="panel-intro">Every building is fully upgraded. Visit the shop to expand your kingdom.</p>'}</div>${button('openPanel','Open building shop',{value:'build',icon:'build',class:'button full-button'})}`);
  }
  buildingGallery(building,spec) {
    const level=Math.max(1,Math.min(spec.maxLevel,this.galleryLevel));
    return `<section class="building-gallery" aria-label="Building evolution gallery"><div class="evolution-preview">${art(building.type,false,level)}<span><strong>${escape(buildingLevelName(spec,level))}</strong><small>${level===building.level?'Your current building':level>building.level?'Future appearance':'Earlier appearance'}</small></span></div><nav class="evolution-levels" aria-label="Choose a building level">${Array.from({length:spec.maxLevel},(_,i)=>i+1).map(n=>`<button data-action="uiGalleryLevel" data-value="${n}" class="evolution-level ${n===level?'selected':''}" aria-pressed="${n===level}" aria-label="Preview ${escape(spec.name)} level ${n}">${art(building.type,false,n)}<span>${n}</span></button>`).join('')}</nav><p>Preview appearances without spending resources. Upgrades still follow the requirements below.</p></section>`;
  }
  equipmentSection(state,id){
    const roster=equipmentRoster(state,id),slots=heroSlots(state,id),ore=Math.max(0,Math.floor(state.ore||0)),open=this.equipHero===id;
    const effectLabel=(key,value)=>({damage:`+${Math.round(value*100)}% damage`,hp:`+${Math.round(value*100)}% hit points`,range:`+${value.toFixed(1)} attack range`,abilityPower:`+${Math.round(value*100)}% ability effect`,abilityDuration:`+${value.toFixed(1)}s ability duration`,abilityTargets:`+${Math.floor(value)} ability target${Math.floor(value)===1?'':'s'}`,abilityRange:`+${value.toFixed(1)} ability range`}[key]||`${key} ${value}`);
    const effectList=effects=>Object.entries(effects).filter(([,v])=>v>0).map(([k,v])=>`<span>${escape(effectLabel(k,v))}</span>`).join('');
    const slotStrip=slots.map(slot=>{
      const item=slot.itemId?EQUIPMENT[slot.itemId]:null,level=slot.itemId?state.equipment?.[slot.itemId]?.level||0:0,key=`${id}:${slot.index}`;
      if(!slot.unlocked)return `<div class="equip-slot locked">${icon('lock')}<span><strong>Slot ${slot.index+1}</strong><small>Hall level ${slot.requires}</small></span></div>`;
      return `<button class="equip-slot ${item?'filled':''} ${this.equipSlot===key?'choosing':''}" data-action="uiSlot" data-value="${key}" aria-expanded="${this.equipSlot===key}" aria-label="${item?`Slot ${slot.index+1}: ${escape(item.name)} level ${level}. Change it.`:`Slot ${slot.index+1} is empty. Choose equipment.`}">${icon(item?'kit':'slot')}<span><strong>${item?escape(item.name):'Empty slot'}</strong><small>${item?`Level ${level}`:'Tap to equip'}</small></span></button>`;
    }).join('');
    const chooser=this.equipSlot?.startsWith(`${id}:`)?(()=>{
      const index=Number(this.equipSlot.split(':')[1]),owned=roster.filter(i=>i.owned);
      return `<div class="equip-chooser" role="group" aria-label="Choose equipment for slot ${index+1}">${owned.length?owned.map(i=>button('equipItem',`${icon('kit')}<span>${escape(i.spec.name)}<small>Level ${i.level}</small></span>`,{value:`${id}:${index}:${i.id}`,class:'button equip-option'})).join(''):'<p class="gate-reason">Forge equipment below before filling this slot.</p>'}${button('equipItem','Leave empty',{value:`${id}:${index}:`,class:'button secondary equip-option'})}</div>`;
    })():'';
    const forge=open?`<div class="forge-list">${roster.map(i=>`<article class="forge-card ${i.unlocked?'':'unavailable'} ${i.equipped?'equipped':''}"><div class="forge-title">${icon('kit')}<span><h4>${escape(i.spec.name)}</h4><small>${i.owned?`Level ${i.level} / ${MAX_EQUIPMENT_LEVEL}${i.equipped?' · equipped':''}`:i.unlocked?'Not forged':`Hall level ${i.spec.unlock}`}</small></span></div><p>${escape(i.spec.description)}</p><div class="forge-effects">${i.owned?effectList(i.current):'<span>No bonus until forged</span>'}</div>${i.level<MAX_EQUIPMENT_LEVEL?`<div class="forge-next"><small>${i.owned?`AT LEVEL ${i.nextLevel}`:'WHEN FORGED'}</small>${effectList(i.next)}</div>`:''}<div class="forge-price">${icon('ore')}<b>${number(i.cost.ore)}</b><span>${i.level>=MAX_EQUIPMENT_LEVEL?'Fully forged':i.owned?'to upgrade':'to forge'}</span></div>${i.reason?`<p class="gate-reason">${escape(i.reason)}</p>`:''}${button('forgeEquipment',i.level>=MAX_EQUIPMENT_LEVEL?'Fully forged':i.owned?`Upgrade to level ${i.nextLevel}`:'Forge',{value:i.id,class:'button primary full-button',disabled:!i.canUpgrade})}</article>`).join('')}</div>`:'';
    return `<div class="hero-equipment"><div class="equip-head">${icon('ore')}<span><strong>${number(ore)} ancient ore</strong><small>Won in battle · never bought</small></span></div><div class="equip-slots">${slotStrip}</div>${chooser}${button('uiEquip',open?`Hide the forge ${icon('up')}`:`Open the forge ${icon('arrow')}`,{value:id,class:'button secondary full-button'})}${forge}</div>`;
  }
  systemPanel(name,snapshot) {
    const s=snapshot.state,catalog=snapshot.catalog,units=snapshot.units;
    if(name==='upgrade') {
      const id=snapshot.upgradeTarget||snapshot.selectedBuilding?.id,info=upgradeInfo(s,id),b=s.buildings.find(x=>x.id===id),c=b&&catalog[b.type];
      if(!info.ok)return this.panelShell(name,'Building information','ROYAL BUILDERS',`<p>${escape(info.reason)}</p>`);
      const maximum=b.level>=c.maxLevel,busy=b.readyAt>0,finish=busy?finishCost(s,'building',id):null;
      const action=busy?button('finish',`Finish now ${icon('gems')} ${number(finish.cost)}`,{value:`building:${id}`,class:'button primary full-button'}):button('confirmUpgrade',maximum?`${icon('check')} Fully upgraded`:`${icon('up')} Upgrade to level ${info.nextLevel}`,{value:id,class:'button primary full-button',disabled:!info.canUpgrade});
      const toolbar=`<section class="upgrade-action-bar" aria-label="Upgrade action"><div class="upgrade-action-summary">${art(b.type,false,b.level)}<div><span class="eyebrow">${maximum?'YOUR BUILDING':busy?'WORK IN PROGRESS':'NEXT IMPROVEMENT'}</span><strong>${maximum?`Level ${b.level} · Complete`:busy?`Level ${b.level} → ${b.upgradingTo||1}`:`Level ${b.level} → ${info.nextLevel}`}</strong><small>${busy?`${icon('time')} ${clock(finish.remaining)} remaining`:maximum?'Every building tier unlocked':`${icon('time')} ${clock(info.duration)} · ${info.freeBuilders} builder${info.freeBuilders===1?'':'s'} free`}</small></div></div><div class="upgrade-action-main">${action}</div>${!maximum&&!busy?`<div class="upgrade-action-cost"><small>UPGRADE COST</small>${cost(info.cost)}</div>`:''}${!maximum&&!busy&&info.reason?`<p class="upgrade-gate" role="status">${icon('info')}${escape(info.reason)}</p>`:''}</section>`;
      const tabs=`<div class="upgrade-tabs" role="tablist" aria-label="Building information">${[['stats','Stats & requirements'],['appearance','Appearance']].map(([id,label])=>`<button type="button" id="upgrade-tab-${id}" role="tab" tabindex="${this.upgradeTab===id?0:-1}" data-action="uiUpgradeTab" data-value="${id}" aria-selected="${this.upgradeTab===id}" aria-controls="upgrade-detail-panel">${label}</button>`).join('')}</div>`;
      const details=this.upgradeTab==='appearance'?`<div class="building-evolution-comparison"><figure>${art(b.type,false,b.level)}<figcaption>Current · ${escape(buildingLevelName(c,b.level))}</figcaption></figure>${!maximum?`${icon('arrow')}<figure>${art(b.type,false,info.nextLevel)}<figcaption>Next · ${escape(buildingLevelName(c,info.nextLevel))}</figcaption></figure>`:''}</div>${button('uiGallery',`${icon('build')} ${this.galleryBuilding===id?'Hide building levels':`Explore all ${c.maxLevel} levels`}`,{value:id,class:'button secondary evolution-toggle'})}${this.galleryBuilding===id?this.buildingGallery(b,c):''}`:`<p class="panel-intro">${escape(c.description)}</p><div class="building-stats ${maximum?'at-max':''}"><div class="comparison-heading"><span>BUILDING STATS</span><span>${maximum?'CURRENT':'CURRENT → NEXT'}</span></div>${statRows(info.current,info.next,undefined,{capacity:info.capacityLabel})}</div>${!maximum&&info.unlocks?`<div class="unlock-callout">${icon('lock')}<span><small>NEXT UNLOCK</small><strong>${escape(info.unlocks)}</strong></span></div>`:''}${!maximum?`<p class="requirement">${escape(info.requires)}</p>`:''}`;
      return this.panelShell(name,escape(c.name),'ROYAL BUILDERS',`<div class="upgrade-details">${tabs}<section id="upgrade-detail-panel" role="tabpanel" aria-labelledby="upgrade-tab-${this.upgradeTab}">${details}</section></div>`,toolbar);
    }
    if(name==='finish') {
      const target=snapshot.finishTarget,info=target?finishCost(s,target.kind,target.id):{ok:false,reason:'Choose a timer to finish.'};
      if(!info.ok)return this.panelShell(name,'Work completed','ROYAL BUILDERS',`<div class="empty-state">${icon('check')}<h3>Already ready!</h3><p>${escape(info.reason)}</p>${button('closePanel','Return to village',{class:'button primary'})}</div>`);
      const label=target.kind==='building'?catalog[s.buildings.find(b=>b.id===target.id)?.type]?.name:target.kind==='hero'?HEROES[target.id]?.name:units[target.id]?.name;
      return this.panelShell(name,'Finish now?','SPEND EARNED GEMS',`<div class="finish-emblem">${icon('gems')}</div><h3 class="finish-title">${escape(label)}</h3><p class="finish-time">${icon('time')}${clock(info.remaining)} remaining</p><p class="panel-intro">Complete this ${target.kind==='research'?'research':'upgrade'} immediately. Your gems are spent once when you confirm.</p><div class="gem-confirm"><span>Finish cost</span><strong>${icon('gems')}${number(info.cost)}</strong><span>Your balance</span><b>${number(s.gems)}</b><span>Balance after spending</span><b>${number(Math.max(0,s.gems-info.cost))}</b></div>${s.gems<info.cost?'<p class="gate-reason">Earn more gems to finish this timer.</p>':''}${button('confirmFinish',`Finish for ${number(info.cost)} ${icon('gems')}`,{value:`${target.kind}:${target.id}`,class:'button primary full-button',disabled:s.gems<info.cost})}${button('closePanel','Keep building',{class:'button secondary full-button'})}`);
    }
    if(name==='research') {
      const lab=s.buildings.find(b=>b.type==='laboratory'),job=s.research,finish=job?finishCost(s,'research',job.type):null;
      return this.panelShell(name,'Royal Workshop','PERMANENT ARMY UPGRADES',`<p class="panel-intro">Preparation is instant. Research makes every future troop stronger.</p>${lab?`<div class="lab-status">${icon('research')}<strong>Workshop level ${lab.level}</strong>${button('openUpgrade','Upgrade',{value:lab.id,class:'button small-button'})}</div>`:`<p class="gate-reason">Build a Royal Workshop to research troop upgrades.</p>${button('selectBuild','Build Royal Workshop',{value:'laboratory',class:'button primary full-button'})}`}${job?`<div class="research-running"><strong>${escape(units[job.type].name)} → level ${job.level}</strong><span>${clock((job.readyAt-Date.now())/1000)} remaining</span>${button('finish',`Finish ${icon('gems')} ${finish?.cost||1}`,{value:`research:${job.type}`,class:'button primary'})}</div>`:''}<div class="research-grid">${Object.keys(units).map(id=>{const i=researchInfo(s,id);return `<article class="research-card"><div class="research-card-title">${art(id,true)}<span><h3>${escape(units[id].name)}</h3><span class="level-pill">Level ${i.level}${i.level<3?` → ${i.nextLevel}`:''}</span></span></div>${statRows(i.current,i.next,['hp','damage','heal'])}<div class="research-price">${cost(i.cost)}<span>${icon('time')}${clock(i.duration)}</span></div>${i.reason?`<p class="gate-reason">${escape(i.reason)}</p>`:''}${button('research',i.level>=3?'Fully researched':`Research level ${i.nextLevel}`,{value:id,class:'button primary full-button',disabled:!i.canResearch})}</article>`;}).join('')}</div>`);
    }
    if(name==='heroes') {
      const hall=s.buildings.find(b=>b.type==='hero_hall');
      const ids=Object.keys(HEROES);
      const focused=ids.includes(this.heroFocus)?this.heroFocus:ids.includes(s.activeHero)?s.activeHero:ids[0];
      this.heroFocus=focused;
      const choices=ids.map(id=>{
        const spec=HEROES[id],info=heroInfo(s,id),active=s.activeHero===id&&info.unlocked;
        return `<button type="button" class="hero-roster-choice ${active?'is-active-hero':''}" data-action="uiHeroFocus" data-value="${id}" aria-pressed="${id===focused}" aria-label="Inspect ${escape(spec.name)}, ${escape(spec.role||spec.title||'hero')}, Hall level ${spec.unlock}${active?', selected champion':''}"><strong>${escape(spec.shortName||spec.name)}</strong><small>${active?'Selected':info.unlocked?`Level ${info.level}`:`Hall ${spec.unlock}`}</small></button>`;
      }).join('');
      const toolbar=`<div class="hero-roster-toolbar"><nav class="hero-roster-tabs" aria-label="Hero roster">${choices}</nav>${hall?button('openUpgrade',`Hall ${hall.level} ${icon('up')}`,{value:hall.id,class:'button secondary hero-hall-control',title:'Upgrade hall'}):button('selectBuild','Build hall',{value:'hero_hall',class:'button primary hero-hall-control'})}</div>`;
      const roster=[focused].map(id=>{
        const i=heroInfo(s,id),selected=s.activeHero===id&&i.unlocked,busy=!!i.readyAt,maximum=i.level>=3;
        const finish=busy?finishCost(s,'hero',id):null,expanded=this.heroDetails.has(id);
        const price=busy?`<div class="hero-action-price"><span>${icon('time')} ${clock((i.readyAt-Date.now())/1000)} remaining</span><span>${icon('gems')} ${number(finish?.cost||1)} to finish now</span></div>`:i.unlocked&&!maximum?`<div class="hero-action-price">${cost(i.cost)}<span>${icon('time')} ${clock(i.duration)}</span></div>`:'';
        const reason=i.reason&&!busy&&!maximum?`<p class="hero-action-reason">${icon('info')}${escape(i.reason)}</p>`:'';
        const actions=i.unlocked?`<div class="hero-profile-actions">${button('selectHero',selected?'Selected':'Choose hero',{value:id,class:`button ${selected?'chosen-button':'secondary'}`,disabled:!i.available||selected})}${busy?button('finish',`Finish now ${icon('gems')} ${number(finish?.cost||1)}`,{value:`hero:${id}`,class:'button primary'}):button('upgradeHero',maximum?'Max level':`Upgrade to level ${i.nextLevel}`,{value:id,class:'button primary',disabled:!i.canUpgrade})}</div>`:hall?button('openUpgrade',`Unlock at Hall level ${i.spec.unlock}`,{value:hall.id,class:'button secondary full-button hero-unlock'}):'';
        const detailId=`hero-details-${id}`;
        const details=expanded?`<section id="${detailId}" class="hero-expanded-details" aria-label="${escape(i.spec.name)} stats and equipment"><div class="hero-ability-title">${icon('hero')}<strong>${escape(i.spec.ability)}</strong></div><p>${escape(i.spec.description)}</p>${i.current?statRows(i.current,i.next,['hp','damage']):''}${i.unlocked?this.equipmentSection(s,id):'<p class="fine-print">Unlock this hero to forge and equip items.</p>'}</section>`:`<section id="${detailId}" class="hero-expanded-details" hidden></section>`;
        return `<article class="hero-profile hero-compact ${i.unlocked?'':'locked'} ${selected?'chosen':''}"><div class="hero-portrait-scene">${heroArt(id)}${selected?'<span class="selected-ribbon">YOUR CHAMPION</span>':''}</div><div class="hero-profile-body"><div class="hero-action-heading"><h3>${escape(i.spec.shortName||i.spec.name)}</h3><span class="level-pill">${i.unlocked?`LEVEL ${i.level}`:`HALL ${i.spec.unlock}`}</span></div><p class="hero-role">${escape(i.spec.title||i.spec.ability)} · ${escape(i.spec.role||'Champion')}<span>Hall ${i.spec.unlock}</span></p>${price}${reason}${actions}<button type="button" class="button hero-details-toggle" data-action="uiHeroDetails" data-value="${id}" aria-expanded="${expanded}" aria-controls="${detailId}">${icon('info')}<span>${expanded?'Hide stats & equipment':'Stats & equipment'}</span>${icon(expanded?'up':'arrow')}</button>${details}</div></article>`;
      }).join('');
      return this.panelShell(name,'Hall of Heroes','PERMANENT CHAMPIONS',`<div class="hero-roster">${roster}</div>`,toolbar);
    }
    if(name==='gems') {
      const builders=s.builders||2,price=builders===2?100:builders===3?200:null,jobs=[...s.buildings.filter(b=>b.readyAt).map(b=>({kind:'building',id:b.id,name:catalog[b.type].name})),...Object.entries(s.heroes).filter(([,h])=>h.readyAt).map(([id])=>({kind:'hero',id,name:HEROES[id].name})),...(s.research?[{kind:'research',id:s.research.type,name:units[s.research.type].name}]:[])];
      return this.panelShell(name,'Gems & builders','EARN IN YOUR KINGDOM',`<div class="gem-wallet">${icon('gems')}<div><strong>${number(s.gems)}</strong><span>YOUR GEMS</span></div><small>Earned in play<br>No real-money purchases</small></div><article class="builder-offer">${icon('hammer')}<div><h3>${builders} royal builders</h3><p>${this.cap.busy} busy · ${builders-this.cap.busy} ready<br>More builders mean more projects at once.</p></div>${button('buyBuilder',price?`Add builder ${icon('gems')} ${price}`:'All builders unlocked',{class:'button primary',disabled:!price||s.gems<price})}</article><h3 class="section-title">Work in progress</h3>${jobs.length?jobs.map(j=>{const f=finishCost(s,j.kind,j.id);return `<div class="timer-job"><span><strong>${escape(j.name)}</strong><small>${clock(f.remaining||0)} remaining</small></span>${button('finish',`Finish ${icon('gems')} ${f.cost||1}`,{value:`${j.kind}:${j.id}`,class:'button primary'})}</div>`;}).join(''):'<p class="panel-intro">Your builders and researchers are ready for a new project.</p>'}<h3 class="section-title">Earn your next gems</h3><div class="achievement-list">${[['first_upgrade','Complete your first upgrade',10],['first_research','Complete your first research',15],...snapshot.raids.map(r=>[`raid_${r.id}`,`First victory: ${r.name}`,25])].map(([id,title,reward])=>`<div class="${s.achievements[id]?'complete':''}">${icon(s.achievements[id]?'check':'target')}<span>${escape(title)}</span><b>${reward}${icon('gems')}</b></div>`).join('')}</div><p class="fine-print">The Gem Garden produces one gem every 30 minutes per level, storing up to 20. Royal League rewards are settled each week.</p>`);
    }
    if(name==='ranked') {
      const r=snapshot.ranked||getRanked(s),left=r.attacksTotal-r.attacksUsed;
      return this.panelShell('attack','Choose your battle','CAMPAIGN & ROYAL LEAGUE',`${this.attackTabs('ranked')}<div class="ranked-hero"><div class="rank-shield">${icon('shield')}<b>${r.tier+1}</b></div><div><span class="eyebrow">ROYAL LEAGUE</span><h3>${escape(r.league)} League</h3><span class="ai-label">LOCAL AI OPPONENTS</span></div></div><div class="league-ladder">${['Copper','Bronze','Silver','Gold','Peacock','Maharaja'].map((n,i)=>`<span class="${i===r.tier?'current':''}">${icon('shield')}<small>${n}</small></span>`).join('')}</div><div class="ranked-stats"><span><strong>#${r.position}</strong><small>Your position</small></span><span><strong>${number(r.score)}</strong><small>Your points</small></span><span><strong>${left}/6</strong><small>Attacks left</small></span></div><p class="league-countdown">${icon('time')} Week ends in ${countdown(r.endsAt-Date.now())}</p>${button('startRanked',left?`Find AI opponent · ${left} attacks left ${icon('army')}`:'All weekly attacks used',{class:'button primary full-button',disabled:!left})}<p class="fine-print">One attack is used when you enter battle. Each star earns 100 points, plus your destruction percentage. Scores are saved on this device.</p><div class="league-rewards"><span>TOP 3 <b>Promote · 30 ${icon('gems')}</b></span><span>4TH–7TH <b>Stay · 15 ${icon('gems')}</b></span><span>8TH–10TH <b>Demote · 5 ${icon('gems')}</b></span></div><p class="reward-note">Play at least one attack to earn a weekly reward.</p>${r.lastReward?`<div class="unlock-callout">${icon('gems')}<span>Last week: #${r.lastReward.position} · ${r.lastReward.gems} gems earned</span></div>`:''}<div class="league-table"><div class="league-table-head"><span>RANK</span><span>KINGDOM</span><span>POINTS</span></div>${r.entries.map(e=>`<div class="league-entry ${e.isPlayer?'is-player':''}"><b>${e.position}</b><span>${escape(e.name)}<small>${e.isPlayer?'YOU':'LOCAL AI'}</small></span><strong>${number(e.score)}</strong></div>`).join('')}</div>${r.history.length?`<h3 class="section-title">Your attacks this week</h3><div class="league-history">${r.history.slice().reverse().map(h=>`<div><strong>${escape(h.opponent)}</strong>${stars(h.stars)}<span>${h.destruction}% · +${h.score} pts</span></div>`).join('')}</div>`:''}`);
    }
  }
  onlinePanel(snapshot){
    const online=snapshot.online||{},registered=!!online.registered,s=snapshot.state;
    const when=value=>{const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms))return '';const m=Math.round(ms/60000);return m<1?'just now':m<60?`${m}m ago`:m<1440?`${Math.round(m/60)}h ago`:`${Math.round(m/1440)}d ago`;};
    const status=online.busy?`<p class="online-status busy">${icon('time')} ${escape(online.busy)}</p>`:online.error?`<p class="gate-reason">${escape(online.error)}</p>`:'';
    if(!registered){
      return this.panelShell('attack','Choose your battle','ONLINE · REAL KINGDOMS',`${this.attackTabs('online')}<div class="online-hero">${icon('globe')}<div><span class="eyebrow">ONLINE PLAY</span><h3>Attack real kingdoms</h3></div></div><p class="panel-intro">Publish your village so other players can attack it, then raid the villages they publish. Trophies move between both kingdoms.</p><div class="online-privacy">${icon('shield')}<p>Joining shares only your kingdom name, your Taj level and your village layout. No account, password, email or save data is sent, and this device is identified by a key generated here.</p></div>${status}${button('joinOnline',`Join online play as ${escape(s.name)} ${icon('arrow')}`,{class:'button primary full-button',disabled:!!online.busy})}<p class="fine-print">Battles are simulated on the attacking device, so results are not verified by the server. Trophy changes, attack limits and rate limits are enforced online.</p>`);
    }
    const opponent=online.opponent,log=online.log||[],board=online.leaderboard||[];
    return this.panelShell('attack','Choose your battle','ONLINE · REAL KINGDOMS',`${this.attackTabs('online')}<div class="online-hero">${icon('trophy')}<div><span class="eyebrow">YOUR STANDING</span><h3>${number(online.trophies||0)} trophies</h3><span class="ai-label">${escape(online.name||s.name)}</span></div></div>${status}<div class="online-actions">${button('publishVillage',online.publishedAt?`Update your defense · ${escape(when(online.publishedAt))}`:`Publish your village ${icon('shield')}`,{class:'button secondary full-button',disabled:!!online.busy})}${button('findOpponent',`Find a real opponent ${icon('army')}`,{class:'button primary full-button',disabled:!!online.busy})}</div>${!online.publishedAt?`<p class="gate-reason">${icon('info')} Publish your village so other players can attack it. Until you do, your defenses never appear online.</p>`:''}${opponent?`<article class="online-opponent"><div class="online-opponent-head">${icon('globe')}<span><strong>${escape(opponent.name)}</strong><small>${number(opponent.trophies)} trophies · Taj level ${opponent.taj_level} · ${opponent.structures} structures</small></span></div><p>Last published ${escape(when(opponent.updated_at))}. Scout the layout and your army before committing.</p>${button('reviewOnline',`Scout this kingdom ${icon('arrow')}`,{class:'button primary full-button'})}</article>`:''}<h3 class="section-title">Global standings</h3>${board.length?`<div class="league-table"><div class="league-table-head"><span>RANK</span><span>KINGDOM</span><span>TROPHIES</span></div>${board.map(e=>`<div class="league-entry ${e.player_id===online.playerId?'is-player':''}"><b>${e.rank}</b><span>${escape(e.name)}<small>${e.player_id===online.playerId?'YOU':`Taj ${e.taj_level} · ${e.attacks_made} attacks`}</small></span><strong>${number(e.trophies)}</strong></div>`).join('')}</div>`:'<p class="panel-intro">No standings loaded yet.</p>'}<h3 class="section-title">Attacks on your village</h3>${log.length?`<div class="league-history">${log.map(entry=>`<div><strong>${escape(entry.attacker_name)}</strong>${stars(entry.stars)}<span>${entry.destruction}% · ${entry.trophy_delta>0?'+':''}${entry.trophy_delta} trophies · ${escape(when(entry.created_at))}</span></div>`).join('')}</div>`:'<p class="panel-intro">No one has attacked your village yet.</p>'}${button('refreshOnline',`Refresh standings ${icon('rotate')}`,{class:'button full-button',disabled:!!online.busy})}<p class="fine-print">Battles run on the attacking device, so results are trusted rather than verified. The server clamps stars, destruction and trophy movement, and limits how often you can attack. ${button('leaveOnline','Leave online play',{class:'button leave-online'})}</p>`);
  }
  catalogPanel(name,snapshot){
    const s=snapshot.state,units=snapshot.units,catalog=snapshot.catalog,filter=this.filters[name],fort=s.buildings.find(b=>b.type==='fort'),barracks=s.buildings.find(b=>b.type==='barracks');
    if(name==='build'){
      const categories={economy:['farm','lumber','mine','granary','market','gem_mine'],defense:['archer_tower','cannon','wall'],army:['barracks','camp','laboratory','hero_hall','stepwell']};
      const entries=Object.entries(catalog).filter(([id])=>filter==='all'||categories[filter]?.includes(id)).sort(([a,ac],[b,bc])=>Number(s.buildings.filter(x=>x.type===a).length>=ac.limit)-Number(s.buildings.filter(x=>x.type===b).length>=bc.limit));
      const toolbar=`<div class="workspace-toolbar"><nav class="catalog-tabs" aria-label="Building categories">${[['all','All'],['economy','Economy'],['defense','Defense'],['army','Army']].map(([id,label])=>`<button data-action="uiFilter" data-value="build:${id}" class="catalog-tab ${filter===id?'active':''}" aria-pressed="${filter===id}">${label}</button>`).join('')}</nav><div class="workspace-summary">${icon('hammer')}<strong>${this.cap.builders-this.cap.busy} builders free</strong><span>${entries.length} buildings</span></div></div>`;
      const content=`<div class="catalog-grid">${entries.map(([id,c])=>{const owned=s.buildings.filter(b=>b.type===id).length,locked=c.unlock>(fort?.level||1),max=owned>=c.limit,short=Object.entries(c.cost).filter(([k,n])=>n>(s.resources[k]||0)),busy=this.cap.busy>=this.cap.builders,reason=locked?`Taj level ${c.unlock} required`:max?'All built':short.length?`Need ${short.map(([k,n])=>`${number(n-s.resources[k])} ${k}`).join(', ')}`:busy?'All builders are busy':'',expanded=this.expandedBuild===id;return `<article class="catalog-card ${max||locked?'unavailable':''}"><button class="catalog-select" data-action="uiBuildDetail" data-value="${id}" aria-expanded="${expanded}" aria-label="Details for ${escape(c.name)}"><span class="catalog-portrait">${art(id)}<span class="catalog-owned">${owned}/${c.limit}</span></span><h3>${escape(c.name)}</h3><span class="catalog-role">${categories.economy.includes(id)?'Economy':categories.defense.includes(id)?'Defense':id==='fort'?'Capital':'Army & support'} ${icon('info')}</span></button><div class="catalog-card-body">${cost(c.cost)}<p class="catalog-status ${reason?'needs-action':''}">${reason?escape(reason):`${clock(c.time)} build · ${c.w} × ${c.h} tiles`}</p>${expanded?`<div class="catalog-detail"><p>${escape(c.description)}</p><span>${number(c.hp)} HP · ${clock(c.time)} build time</span>${locked&&fort?button('openUpgrade','Upgrade Taj',{value:fort.id,class:'button secondary full-button'}):max&&s.buildings.find(b=>b.type===id)?button('openUpgrade','View your building',{value:s.buildings.find(b=>b.type===id).id,class:'button secondary full-button'}):''}</div>`:''}${button(id==='wall'?'startWallLine':'selectBuild',max?'Built':locked?'Locked':`Build ${icon('plus')}`,{value:id,class:'button primary full-button',disabled:locked||max||!!short.length||busy,title:`Build ${c.name}`})}</div></article>`;}).join('')}</div><p class="workspace-footnote">Choose a building, position it on open ground, then confirm. Tap its portrait for details.</p>`;
      return this.panelShell('build','Build your kingdom','ROYAL BUILDERS',content,toolbar);
    }
    const ready=id=>(barracks?.level||0)>=units[id].unlock,entries=Object.entries(units).filter(([id])=>filter==='all'||(filter==='ready'?ready(id):!ready(id)));
    const toolbar=`<div class="workspace-toolbar"><div class="army-summary"><span>${icon('army')}<strong>${this.cap.used}<small> / ${this.cap.army} space</small></strong></span>${button('quickTrain','Quick fill',{class:'button primary',title:'Quick train a balanced army'})}</div><div class="capacity-track"><i style="width:${Math.min(100,this.cap.used/this.cap.army*100)}%"></i></div>${snapshot.preview?button('reviewBattle',`Review battle ${icon('arrow')}`,{class:'button review-battle full-button'}):''}<div class="army-toolbar-row"><nav class="catalog-tabs" aria-label="Troop availability">${[['ready','Ready'],['all','All'],['locked','Locked']].map(([id,label])=>`<button class="catalog-tab ${filter===id?'active':''}" data-action="uiFilter" data-value="army:${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</nav>${button('uiArmyTools',`${icon('settings')} Tools`,{class:'button army-tools-toggle',title:'Army recipes, research and practice'})}</div>${this.armyTools?`<div class="army-toolbox">${button('saveArmyRecipe','Save army',{icon:'check'})}${button('loadArmyRecipe','Load saved army',{icon:'rotate',disabled:!snapshot.hasArmyRecipe})}${button('clearArmy','Clear army',{icon:'minus',disabled:!this.cap.used})}${button('openPanel','Research',{value:'research',icon:'research'})}${button('startPractice','Test defenses',{icon:'shield'})}<p>Preparation is free and instant. Practice returns every troop and gives no rewards.</p></div>`:''}</div>`;
    const composition=Object.entries(s.army).filter(([,n])=>n>0);
    const content=`<div class="army-composition" aria-label="Your current army"><div class="composition-heading"><strong>Your army</strong><span>${this.cap.used}/${this.cap.army} space</span></div><div class="composition-portraits">${composition.map(([id,n])=>`<span title="${escape(units[id].name)}">${art(id,true)}<b>×${n}</b><small>${escape(units[id].name)}</small></span>`).join('')||'<p>Choose warriors below, or use Quick fill.</p>'}</div></div><div class="army-card-grid">${entries.map(([id,u])=>{const locked=!ready(id),e=effectiveUnit(s,id),count=s.army[id]||0,full=this.cap.used+u.space>this.cap.army,expanded=this.expandedUnit===id;return `<article class="army-roster-card ${locked?'unavailable':''}"><button class="roster-select" data-action="uiUnitDetail" data-value="${id}" aria-expanded="${expanded}" aria-label="Details for ${escape(u.name)}">${art(id,true)}<span class="roster-title"><h3>${escape(u.name)}</h3><span>${u.space} space · Level ${e.level}</span></span>${icon('info')}</button>${expanded?`<div class="catalog-detail"><p>${escape(u.description)}</p><div class="roster-stats"><span><b>${number(e.hp)}</b> HP</span><span><b>${number(e.heal||e.damage)}</b> ${e.heal?'heal':'damage'}</span><span><b>${u.range}</b> range</span></div><p>Targets: ${escape(u.targetLabel||unitTargets[id]||'nearest structure')}</p>${!locked?button('train','Add 5',{value:id,count:5,class:'button secondary',disabled:this.cap.used+u.space*5>this.cap.army}):''}</div>`:''}${locked?`<div class="roster-unlock">${icon('lock')}<span>Akhara level ${u.unlock}</span>${barracks?button('openUpgrade','View upgrade',{value:barracks.id,class:'button secondary'}):''}</div>`:`<div class="roster-controls">${button('removeTroop','',{value:id,icon:'minus',class:'icon-button',disabled:!count,title:`Remove ${u.name}`})}<span><strong>${count}</strong><small>in army</small></span>${button('train','',{value:id,icon:'plus',class:'icon-button roster-add',disabled:full,title:`Add ${u.name}`})}</div>`}</article>`;}).join('')}</div>${!entries.length?'<div class="empty-state"><h3>All troops are available</h3><p>Choose Ready to prepare your army.</p></div>':''}<div class="army-next-step"><p>${this.cap.army-this.cap.used} spaces remaining. Heroes return after every battle.</p>${button('openPanel',`Choose a battle ${icon('arrow')}`,{value:'attack',class:'button primary'})}</div>`;
    return this.panelShell('army','Prepare your army','FREE · INSTANT · YOUR COMPOSITION',content,toolbar);
  }
  briefingPanel(snapshot){
    const p=snapshot.preview,b=p?.battle,s=snapshot.state;if(!b)return this.panelShell('briefing','Battle briefing','SCOUT BEFORE YOU COMMIT','<p class="panel-intro">Choose an opponent from Attack to preview its defenses.</p>');
    const catalog=snapshot.catalog,units=snapshot.units,practice=p.kind==='practice',ranked=p.kind==='ranked',online=p.kind==='online',army=Object.entries(s.army).filter(([,n])=>n>0),defenses=b.buildings.filter(x=>catalog[x.type]?.damage),hero=b.hero,spellCount=Object.values(b.spells||{}).filter(n=>n>0).length;
    const map=`<svg class="briefing-map" viewBox="-1 -1 26 26" role="img" aria-label="Top-down layout: ${defenses.length} defenses. Taj is gold, defenses red, walls brown."><title>${escape(b.raid?.name||'Battle layout')}</title><defs><pattern id="scout-grid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M 1 0 L 0 0 0 1" fill="none" stroke="#d8ddad" stroke-width=".035"/></pattern></defs><rect x="0" y="0" width="24" height="24" rx=".5" fill="#8ea36c"/><rect x="0" y="0" width="24" height="24" fill="url(#scout-grid)"/><rect x=".15" y=".15" width="23.7" height="23.7" rx=".4" fill="none" stroke="#f2d783" stroke-width=".35"/>${b.buildings.map(x=>`<rect x="${x.x+.08}" y="${x.z+.08}" width="${Math.max(.2,x.w-.16)}" height="${Math.max(.2,x.h-.16)}" rx=".16" fill="${x.type==='fort'?'#f6dfa0':catalog[x.type]?.damage?'#bc6550':x.type==='wall'?'#766342':'#e0d4af'}" stroke="#4e6047" stroke-width=".09"/>${x.type==='fort'?`<text x="${x.x+x.w/2}" y="${x.z+x.h/2+.35}" text-anchor="middle" font-size="1.3" font-weight="bold" fill="#785521">T</text>`:''}`).join('')}</svg>`;
    const content=`<div class="briefing-layout"><section class="scout-card">${map}<div class="map-legend"><span><i class="legend-taj"></i>Taj</span><span><i class="legend-defense"></i>Defense</span><span><i class="legend-wall"></i>Walls</span><span>Gold edge: deployment</span></div><h3>${escape(b.raid?.name||'Your defenses')}</h3><p>${defenses.length} defenses · ${b.buildings.length} structures · ${clock(b.duration||180)}</p><div class="defense-counts">${Object.keys(catalog).filter(id=>catalog[id].damage).map(id=>[id,b.buildings.filter(x=>x.type===id).length]).filter(([,n])=>n).map(([id,n])=>`<span>${escape(catalog[id].name)} <b>×${n}</b></span>`).join('')}</div></section><section class="briefing-army"><div class="briefing-section-title"><h3>Your force</h3>${button('editArmyFromBriefing','Edit army',{class:'button secondary'})}</div><strong class="briefing-space">${this.cap.used} / ${this.cap.army} army space</strong><div class="briefing-troops">${army.map(([id,n])=>`<span title="${escape(units[id].name)}">${art(id,true)}<b>×${n}</b><small>${escape(units[id].name)}</small></span>`).join('')}</div>${!army.length?'<p class="gate-reason">Your army is empty. Prepare troops before attacking.</p>':''}<div class="readiness-row">${icon('hero')}<div><strong>${hero?escape(hero.name):'No hero ready'}</strong><p>${hero?'One ability · your hero always returns':'Choose an available champion in the Hall of Heroes.'}</p></div></div><div class="readiness-row">${icon('research')}<div><strong>${spellCount} / 4 spells prepared</strong><p>${spellCount?'Lightning · Freeze · Rage · Monsoon':'Build a Sacred Stepwell to prepare spells.'}</p></div></div></section></div><div class="battle-commit-note">${icon('info')}<p>${online?`A real player's published village. Winning stars moves trophies to you; losing moves them to ${escape(b.opponent?.name||'them')}. Deployed troops are consumed; unused troops and your hero return.`:practice?'Practice attacks your own layout. Every troop returns; no rewards or league attempts are earned or spent.':ranked?'Starting uses one of your six weekly League attacks. Deployed troops are consumed; unused troops and your hero return.':'Deployed troops are consumed. Unused troops and your hero return. The clock starts only when you confirm.'}</p></div><div class="briefing-actions">${button('closePanel','Cancel',{class:'button secondary'})}${button('confirmBattle',practice?'Start practice':online?`Attack this kingdom ${icon('army')}`:`Attack now ${icon('army')}`,{class:'button primary',disabled:!army.length&&!hero})}</div>`;
    return this.panelShell('briefing',online?`Attack ${escape(b.opponent?.name||'a rival kingdom')}`:practice?'Test your defenses':'Battle briefing',online?'ONLINE · A REAL PLAYER':ranked?'ROYAL LEAGUE · LOCAL AI':practice?'PRACTICE · NOTHING TO LOSE':'CAMPAIGN · SCOUT & PREPARE',content);
  }
  panel(name, snapshot) {
    if(name==='builders')return this.buildersPanel(snapshot);
    if(name==='build'||name==='army')return this.catalogPanel(name,snapshot);
    if(name==='briefing')return this.briefingPanel(snapshot);
    if(name==='retreat')return this.panelShell('retreat','Leave this battle?','BATTLE PAUSED',`<div class="retreat-summary">${stars(snapshot.battle?.stars||0)}<strong>${Math.floor(snapshot.battle?.destruction||0)}% destruction</strong></div><p class="panel-intro">${snapshot.battle?.kind==='practice'?'Your full army will return. This practice gives no rewards.':'The battle ends now. Deployed troops are consumed; unused troops and your hero return.'}</p><div class="briefing-actions">${button('cancelRetreat','Keep fighting',{class:'button primary'})}${button('confirmRetreat','Retreat',{class:'button danger'})}</div>`,'','cancelRetreat');
    if (['upgrade','finish','research','heroes','gems'].includes(name)) return this.systemPanel(name,snapshot);
    const attack=name==='attack'; if(attack&&snapshot.attackTab==='online') return this.onlinePanel(snapshot); if(attack&&snapshot.attackTab==='ranked') return this.systemPanel('ranked',snapshot); if(attack) name='map';
    const {state:s,catalog,units,raids} = snapshot, headings = {build:['THE ROYAL WORKSHOP','Build your kingdom'],army:['WARRIOR AKHARA','Gather your army'],map:['THE SIX ROADS','Campaign'],chronicle:['A KINGDOM WORTH BUILDING','The valley chronicle'],settings:['MAKE IT YOURS','Your kingdom'],help:['THE ART OF COMMAND','Field guide']};
    const [eyebrow,title] = headings[name] || headings.build;
    let content = '';
    if (name === 'map') {
      const totalStars = Object.values(s.raidStars).reduce((a,b) => a+b,0);
      content = `<div class="campaign-intro"><span class="map-compass">${icon('map')}</span><div><span class="eyebrow">RECLAIM THE RIVER ROUTES</span><p>The Iron Regent has silenced the valley.<br>Six roads. Six battles. One monsoon.</p></div><span class="campaign-stars">${icon('star')} ${totalStars}/18</span></div><div class="campaign-route">${raids.map((r,i) => {const unlocked = i===0 || s.raidStars[raids[i-1].id] > 0, won = s.raidStars[r.id] || 0; return `<article class="raid-card ${unlocked ? 'unlocked' : 'locked'} ${won ? 'won' : ''}"><div class="route-marker">${unlocked ? String(i+1).padStart(2,'0') : icon('lock')}</div><div class="raid-landmark">${art(['stepwell','archer_tower','market','hero_hall','cannon','fort'][i],false,Math.min(15,i+1))}</div><div class="raid-region"><span class="eyebrow">${escape(r.region)}</span>${stars(won)}</div><h3>${escape(r.name)}</h3><p>${escape(r.story)}</p>${unlocked ? `<div class="raid-brief">${icon('shield')}<span>${escape(r.briefing)}</span></div>` : ''}<div class="raid-rewards"><small>${won ? 'THREE-STAR BASE · REPEATS REDUCED' : 'THREE-STAR VICTORY REWARD'}</small>${cost({...r.reward,...(!won?{gems:25}:{})})}</div>${button('startRaid',unlocked ? `${won ? 'Raid again' : 'March to battle'} ${icon('arrow')}` : 'Win the previous battle to unlock',{value:r.id,class:'button primary raid-start',disabled:!unlocked})}</article>`;}).join('')}</div>`;
    } else if (name === 'chronicle') {
      const won = Object.values(s.raidStars).filter(n => n>0).length;
      const tasks = [
        {chapter:'01',title:'A home before an empire',body:'The first rains have reached Surajgarh. Your people have raised a palace beside the old stepwell. Give them a home that will endure.',items:[[s.buildings.some(b=>b.type==='farm'),'Establish the rice fields'],[s.buildings.some(b=>b.type==='market'),'Open the spice bazaar'],[(s.buildings.find(b=>b.type==='fort')?.level||1)>=2,'Raise Taj Mahal to level 2']]},
        {chapter:'02',title:'The roads remember',body:'Beyond the teak forests, caravans wait at closed gates. An army can take a road. A kingdom must give people a reason to travel it.',items:[[won>=1,'Free the Konkan river crossing'],[won>=3,'Reopen the ancient salt road'],[(s.buildings.find(b=>b.type==='barracks')?.level||1)>=2,'Train the next generation at a level 2 Akhara']]},
        {chapter:'03',title:'Return of the monsoon',body:'The Iron Regent holds the headwaters. Carry the banners of the free villages to his citadel and let the river find its way home.',items:[[won>=4,'Open the artisan gates'],[won>=5,'Light the Amber signal'],[won>=6,'Break the Regent’s hold and return the rains']]},
      ];
      content = `<p class="panel-intro">Not every legacy is carved in stone. Some are carried by rivers.</p><div class="chapters">${tasks.map(t => `<article class="chapter"><span class="chapter-number">${t.chapter}</span><span class="eyebrow">CHAPTER ${t.chapter}</span><h3>${t.title}</h3><p>${t.body}</p><ul>${t.items.map(([done,text])=>`<li class="${done?'complete':''}">${icon(done?'check':'target')}<span>${text}</span></li>`).join('')}</ul></article>`).join('')}</div>`;
    } else if (name === 'settings') {
      content = `<div class="settings-crest">${icon('fort')}<span class="eyebrow">A NAME TO REMEMBER</span></div><form id="name-form"><label for="kingdom-name">Kingdom name</label><div class="name-field"><input id="kingdom-name" name="name" value="${escape(s.name)}" maxlength="28" minlength="1" required autocomplete="off">${button('saveName','Save',{class:'button primary'})}</div></form><div class="settings-row"><span>${icon('sound')}<span><strong>Sounds of the valley</strong><small>Effects, birdsong and battle · preference saved</small></span></span>${button('toggleSound',snapshot.soundEnabled === false ? 'Off' : 'On',{class:'button sound-toggle',title:'Toggle sound'})}</div><div class="settings-row"><span>${icon('music')}<span><strong>Raga score</strong><small>Bansuri and tabla at home, shehnai and dhol in battle</small></span></span>${button('toggleMusic',snapshot.musicEnabled === false ? 'Off' : 'On',{class:'button sound-toggle',title:'Toggle music',disabled:snapshot.soundEnabled===false})}</div><div class="settings-row volume-row"><label for="volume-master"><strong>Volume</strong><small>All sound</small></label><input id="volume-master" type="range" min="0" max="100" step="1" data-volume="master" value="${Math.round((snapshot.volumes?.master??.8)*100)}" aria-label="Master volume"></div><div class="settings-row volume-row"><label for="volume-music"><strong>Music volume</strong><small>Score and ambience</small></label><input id="volume-music" type="range" min="0" max="100" step="1" data-volume="music" value="${Math.round((snapshot.volumes?.music??.55)*100)}" aria-label="Music volume"></div><div class="settings-row quality-row"><label for="graphics-quality"><strong>Graphics quality</strong><small>Balance detail and battery life</small></label><select id="graphics-quality">${[['low','Low'],['balanced','Balanced'],['ultra','Ultra']].map(([value,label])=>`<option value="${value}" ${(snapshot.quality||'balanced')===value?'selected':''}>${label}</option>`).join('')}</select></div><div class="settings-note">${icon('shield')}<p>Your kingdom saves locally and syncs to your Google account. Keep this tab open while syncing. Export a backup before clearing browser data. Import replaces the current kingdom.</p></div>${button('openAccount','Google account & sync',{icon:'shield',class:'button full-button'})}<div class="save-actions">${button('exportSave','Export kingdom',{icon:'shield',class:'button secondary'})}${button('importSave','Import kingdom',{icon:'up',class:'button secondary'})}</div>${button('restartTutorial',`${icon('target')} Replay the guided start ${icon('arrow')}`,{class:'button full-button guide-link'})}${button('openPanel',`${icon('book')} Open field guide ${icon('arrow')}`,{value:'help',class:'button full-button guide-link'})}${button('openPanel',`${icon('book')} Valley chronicle ${icon('arrow')}`,{value:'chronicle',class:'button full-button guide-link'})}`;
    } else if(name==='help') {
      content=`<p class="panel-intro">A small kingdom. A great many possibilities. Your guide to building, commanding and bringing the valley home.</p><div class="field-guide">${[
        ['move','Explore your village','Drag empty ground to move the view. Scroll or pinch to zoom; use the camera buttons to rotate and recenter. Tap a building for information, upgrades and moving.'],
        ['build','Build with intention','Choose Build, select a structure, then tap open ground and confirm. Walls use two endpoints to make a straight line. Upgrade Taj Mahal to open new possibilities.'],
        ['army','Prepare your army','Troops are instant and free, limited by camp space. Add or remove them in Army; Quick train creates a balanced force. The Royal Workshop improves future troops. In battle, swipe the troop cards, select a unit and tap the outer deployment band.'],
        ['hero','Lead with a champion','Choose an unlocked champion in the Hall of Heroes. Select their battle card, deploy at the outer edge, then tap it again for their once-per-battle ability. Heroes always return.'],
        ['kit','Forge hero equipment','Winning battles earns Ancient Ore. In the Hall of Heroes, open the forge to craft and improve equipment, then place it in a hero slot. The second slot opens at Hall level 3. Equipment changes stats and the hero ability itself; upgrades are instant and never use a builder.'],
        ['lightning','Choose the right spell','Lightning strikes structures. Freeze silences defenses for a short time. Rage strengthens troops in its area. Select a spell, then tap the battlefield to cast; Cancel or Esc leaves aiming mode. Monsoon heals your army when a stepwell is available.'],
        ['shield','Practice your defenses','Army → Test defenses lets you attack your own layout. Your full army returns and no rewards are earned. Campaign and League consume deployed troops; unused reserves return.'],
        ['gems','Earn every gem','First victories, milestones, the Gem Garden and weekly League rewards earn gems. Spend them on builders or finishing work. There are no real-money purchases.'],
        ['map','A league on your device','Royal League is a local AI competition, with six attacks each week. Stars and destruction earn points. These are simulated rivals, not online players. Your kingdom and league live in this browser.'],
        ['settings','Keep your kingdom','Export a backup from Settings. Import restores it and replaces your current kingdom. Sound and graphics preferences stay on this device. Press Esc or the close button to leave a panel.']
      ].map(([glyph,title,body])=>`<article class="guide-section"><span>${icon(glyph)}</span><div><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div>${button('openPanel','Back to settings',{value:'settings',class:'button full-button'})}`;
    }
    if(attack) content=this.attackTabs('campaign')+content;
    return this.panelShell(name,attack?'Choose your battle':title,eyebrow,content);
  }
  toast(text) { clearTimeout(this.toastTimer); const el = document.getElementById('toast'); el.textContent = text; el.classList.add('visible'); this.toastTimer = setTimeout(() => el.classList.remove('visible'), 3800); }
  setLoading(progress, text) { const value = Math.max(0,Math.min(1,progress > 1 ? progress / 100 : progress)); document.getElementById('loading-progress').style.width = `${value*100}%`; document.getElementById('loading-label').textContent = text || 'Preparing your kingdom…'; if(value>=1) {document.getElementById('loading').classList.add('loaded'); setTimeout(()=>document.getElementById('loading').hidden=true,600);} }
  showResult(result) {
    const first=this.result!==result||!document.querySelector('#result-host .result-card');this.result = result;
    const deployed=Object.entries(result.deployed||{}).filter(([id,n])=>n>0&&this.snapshot?.units?.[id]);
    const star='<svg viewBox="0 0 24 24" aria-hidden="true"><path class="star-socket" d="m12 2 3 6.5 7 .9-5.1 5 .9 7-5.8-3.3-5.8 3.3.9-7-5.1-5 7-.9L12 2Z"/><path class="star-gold" fill="url(#cobStarGold)" d="m12 2 3 6.5 7 .9-5.1 5 .9 7-5.8-3.3-5.8 3.3.9-7-5.1-5 7-.9L12 2Z"/></svg>';
    const banner=result.practice?'DEFENSE TEST':result.victory?'VICTORY':'DEFEAT',destruction=Math.floor(result.destruction||0);
    this.update('result-host', `<div class="result-backdrop ${result.victory?'victory':'defeat'}"><svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><linearGradient id="cobStarGold" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff4c2"/><stop offset=".45" stop-color="#ffcf4d"/><stop offset="1" stop-color="#e0901e"/></linearGradient></defs></svg><div class="result-rays"></div><canvas class="result-confetti" aria-hidden="true"></canvas><section class="result-card royal" role="dialog" aria-modal="true" aria-labelledby="result-title"><div class="result-banner">${banner}</div><div class="result-head"><div class="result-starline" role="img" aria-label="${result.stars} of 3 stars">${[0,1,2].map(()=>`<span class="star-slot">${star}</span>`).join('')}</div><span class="eyebrow">${result.practice ? 'YOUR DEFENSES, PUT TO THE TEST' : result.victory ? 'THE VALLEY IS WITH YOU' : 'EVERY BATTLE TEACHES'}</span><h2 id="result-title">${escape(result.title || (result.victory ? 'A road reclaimed' : 'Regroup and return'))}</h2><p>${escape(result.story || '')}</p><span class="result-destruction"><b data-count="${destruction}">${destruction}</b>% destruction</span><div class="result-meter"><i style="width:0"></i></div></div><div class="result-summary"><div class="result-loot"><small>${result.practice?'FULL ARMY RESTORED':'RESOURCES BROUGHT HOME'}</small>${result.practice?'<p class="empty-loot">No rewards are earned in defense practice.</p>':Object.values(result.reward || result.loot || {}).some(n => n > 0) ? cost(result.reward || result.loot) : '<p class="empty-loot">No resources gained this time.</p>'}</div>${!result.practice&&result.gems?`<div class="result-bonus">${icon('gems')} +${result.gems} first-victory gems</div>`:''}${!result.practice&&result.ore?`<div class="result-bonus">${icon('ore')} +${result.ore} ancient ore for hero equipment</div>`:''}${result.online&&result.trophyDelta!=null?`<div class="result-bonus">${icon('trophy')} ${result.trophyDelta>0?'+':''}${result.trophyDelta} trophies · ${number(result.trophies||0)} total</div>`:''}${result.online&&result.trophyError?`<p class="overflow-note">${escape(result.trophyError)}</p>`:''}${!result.practice&&result.ranked?`<div class="result-bonus">${icon('shield')} +${result.scoreGain} league points · #${result.ranked.position}</div>`:''}${!result.practice&&Object.values(result.overflow||{}).some(n=>n>0)?`<p class="overflow-note">Storage full: ${Object.entries(result.overflow).filter(([,n])=>n>0).map(([k,n])=>`${number(n)} ${k}`).join(', ')} could not be stored.</p>`:''}${deployed.length?`<div class="result-troops"><small>TROOPS DEPLOYED${result.practice?' · RESTORED':''}</small><div>${deployed.map(([id,n])=>`<span title="${escape(this.snapshot.units[id].name)}">${art(id,true)}<b>×${n}</b></span>`).join('')}</div></div>`:''}</div>${button('dismissResult',`Return to your kingdom ${icon('arrow')}`,{class:'button primary'})}</section></div>`);
    if(first)this.playResultFx(result);else{const host=document.getElementById('result-host');host.querySelectorAll('.star-slot').forEach((slot,i)=>slot.classList.add(i<result.stars?'earned':'missed'));const meter=host.querySelector('.result-meter i');if(meter)meter.style.width=`${destruction}%`;}
  }
  // Choreography: banner unfurls, stars land one by one, numbers count up, confetti falls.
  playResultFx(result) {
    this.stopResultFx();const host=document.getElementById('result-host'),canvas=host.querySelector('.result-confetti');
    this.confetti=canvas?new ConfettiField(canvas):null;
    this.cancelStars=starSequence(host,result.stars||0,{confetti:this.confetti,onStar:i=>this.actions.resultStar?.(i)});
    const meter=host.querySelector('.result-meter i');requestAnimationFrame(()=>requestAnimationFrame(()=>{if(meter)meter.style.width=`${Math.floor(result.destruction||0)}%`;}));
    countUp(host.querySelector('[data-count]'),Math.floor(result.destruction||0),{duration:1400,delay:300});
    host.querySelectorAll('.result-loot .cost > span').forEach((el,i)=>{const node=[...el.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);const value=Number(String(node?.nodeValue||'').replace(/[^0-9]/g,''));if(node&&value){const text=document.createElement('b');text.style.fontWeight='inherit';node.replaceWith(text);countUp(text,value,{duration:1100,delay:700+i*120});}});
    if(result.victory&&!result.practice)this.fxTimers=[setTimeout(()=>this.confetti?.shower(3.2),650+Math.max(1,result.stars)*560)];
  }
  stopResultFx() { this.cancelStars?.();this.cancelStars=null;for(const t of this.fxTimers||[])clearTimeout(t);this.fxTimers=[];this.confetti?.dispose();this.confetti=null; }
  battleIntro(title,subtitle) { curtain(title,subtitle); }
  starEarned(index) { flyStar(index); }
  flyResources(point,amounts) { for(const [key,amount] of Object.entries(amounts||{}))if(amount>0)flyToHud(point,key,amount,icon(key)); }

}
